@startuml

left to right direction
skinparam actorStyle stick
skinparam usecase {
    BackgroundColor #fefefe
    BorderColor #555
}
skinparam rectangle {
    BorderColor #444
    FontStyle bold
}

actor "Admin" as Admin
actor "Moderador" as Mod
actor "Operador" as Op

Mod --|> Admin
Op --|> Admin

rectangle "Plataforma mesominds" {
    usecase "Gerenciar Conteúdos" as UC_Main

    usecase "Criar Conteúdo" as UC_Create
    usecase "Editar Conteúdo" as UC_Edit
    usecase "Deletar Conteúdo" as UC_Delete
    usecase "Visualizar Conteúdo" as UC_View
    usecase "Atualizar status Conteúdo" as UC_Update_Status

    UC_Main <.. UC_Create : include
    UC_Main <.. UC_Edit : include
    UC_Main <.. UC_Delete : include
    UC_Main <.. UC_View : include
    UC_Main <.. UC_Update_Status : include

}

Admin --> UC_Main

@enduml