@startuml
left to right direction
skinparam actorStyle stick
skinparam usecase {
  BackgroundColor #fefefe
  BorderColor #555
}
skinparam rectangle {
  BorderColor #444
  FontStyle bold
}

actor "Admin" as Admin
actor "Moderador" as Mod
actor "Operador" as Op

Mod --|> Admin
Op --|> Admin

rectangle "Plataforma Mesominds" {
    usecase "Gerenciar Plataforma" as UC_Main
    usecase "Gerenciar conteúdos" as UC_Content
    usecase "Gerenciar questões" as UC_Questions
    usecase "Gerenciar atividades" as UC_Activities
    usecase "Gerenciar simulados" as UC_Simulations
    usecase "Gerenciar usuários" as UC_Users
    usecase "Gerenciar turmas" as UC_Classes
    
    UC_Main <.. UC_Content : include
    UC_Main <.. UC_Questions : include
    UC_Main <.. UC_Activities : include
    UC_Main <.. UC_Simulations : include
    UC_Main <.. UC_Users : include
    UC_Main <.. UC_Classes : include
}

Admin --> UC_Main

@enduml